import { afterEach, expect, test } from 'bun:test';
import { execSync, spawn, spawnSync } from 'node:child_process';
import { existsSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, unlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { listMutationTasks, runTaskMutate, simpleMutations } from '../x-build/lib/x-build/mutate.mjs';

const roots=[];
let worktreeIndex=0;
const makeRoot=(prefix='mutate-audit-')=>{const root=mkdtempSync(join(tmpdir(),prefix));roots.push(root);execSync('git init -q && git config user.email test@example.com && git config user.name Test',{cwd:root,shell:'/bin/bash'});return root;};
const commit=(root,file,content)=>{writeFileSync(join(root,file),content);execSync(`git add ${JSON.stringify(file)} && git commit -qm fixture`,{cwd:root,shell:'/bin/bash'});};
const artifact=(state,task,data,project='p')=>{let worktree=data.worktree,branch=data.branch;if(!worktree){worktree=state+`-wt-${++worktreeIndex}`;branch=`mutate-${worktreeIndex}`;roots.push(worktree);execSync(`git worktree add -qb ${JSON.stringify(branch)} ${JSON.stringify(worktree)}`,{cwd:state,shell:'/bin/bash'});}else if(!branch){branch=execSync('git branch --show-current',{cwd:worktree,encoding:'utf8'}).trim();}const dir=join(state,'.xm/build/projects',project,'worktrees',task);mkdirSync(dir,{recursive:true});writeFileSync(join(dir,'run.json'),JSON.stringify({task_id:task,branch,worktree,...data}));return worktree;};
const tasks=(state,project,rows)=>{const dir=join(state,'.xm/build/projects',project,'phases/02-plan');mkdirSync(dir,{recursive:true});writeFileSync(join(dir,'tasks.json'),JSON.stringify({tasks:rows}));};
afterEach(()=>{for(const root of roots.splice(0))try{rmSync(root,{recursive:true,force:true});}catch{}});

test('non-green baseline exits 2 before mutants or ledger rows',async()=>{const root=makeRoot();commit(root,'a.js','const value = true;');artifact(root,'T1',{target:'a.js',test_command:'false',changed_lines:[1]});let error;try{await runTaskMutate(root,'T1');}catch(caught){error=caught;}expect(error?.exitCode).toBe(2);expect(error?.report).toMatchObject({project:'p',baseline_exit_code:1,mutants:[]});expect(existsSync(join(root,'.xm/review/escape-ledger.jsonl'))).toBe(false);expect(JSON.parse(readFileSync(join(root,'.xm/review/mutate/p/T1.json'),'utf8')).mutants).toEqual([]);});

test('detected package script runs through bun run test',async()=>{const root=makeRoot();commit(root,'a.js','const value = true;');const wt=artifact(root,'T1',{target:'a.js',changed_lines:[1]});writeFileSync(join(wt,'package.json'),JSON.stringify({scripts:{test:'touch script-ran'}}));writeFileSync(join(wt,'bun.lock'),'');const report=await runTaskMutate(root,'T1',{maxMutants:1});expect(report).toMatchObject({baseline_exit_code:0,test_command:'bun run test',test_command_source:'package:bun'});expect(existsSync(join(wt,'script-ran'))).toBe(true);});

test('symlink target is rejected before external bytes change',async()=>{const root=makeRoot(),outside=join(tmpdir(),`mutate-outside-${process.pid}-${Date.now()}.js`);writeFileSync(outside,'const external = true;');commit(root,'a.js','const internal = true;');const wt=artifact(root,'T1',{target:'a.js',test_command:'true',changed_lines:[1]});unlinkSync(join(wt,'a.js'));symlinkSync(outside,join(wt,'a.js'));try{await expect(runTaskMutate(root,'T1')).rejects.toThrow(/non-symlink/);expect(readFileSync(outside,'utf8')).toBe('const external = true;');}finally{rmSync(outside,{force:true});}});

test('linked worktree mutates branch bytes but stores report in main state root',async()=>{const main=makeRoot('mutate-main-');commit(main,'a.js','const main = true;');const wt=main+'-wt';roots.push(wt);execSync(`git worktree add -qb feature ${JSON.stringify(wt)}`,{cwd:main,shell:'/bin/bash'});writeFileSync(join(wt,'a.js'),'const branch = false;');execSync('git add a.js && git commit -qm branch',{cwd:wt,shell:'/bin/bash'});artifact(main,'T1',{target:'a.js',test_command:'true',changed_lines:[1],worktree:wt});const report=await runTaskMutate(main,'T1',{workspaceRoot:main,stateRoot:main,maxMutants:1});expect(report).toMatchObject({project:'p',counts:{survived:1}});expect(readFileSync(join(main,'a.js'),'utf8')).toBe('const main = true;');expect(readFileSync(join(wt,'a.js'),'utf8')).toBe('const branch = false;');expect(existsSync(join(main,'.xm/review/mutate/p/T1.json'))).toBe(true);expect(existsSync(join(wt,'.xm/review/mutate/p/T1.json'))).toBe(false);});

test('linked-worktree mutate CLI resolves main state and task worktree source',()=>{const main=makeRoot('mutate-cli-main-');commit(main,'a.js','const main = true;');const wt=main+'-wt';roots.push(wt);execSync(`git worktree add -qb cli-feature ${JSON.stringify(wt)}`,{cwd:main,shell:'/bin/bash'});writeFileSync(join(wt,'a.js'),'const branch = false;');execSync('git add a.js && git commit -qm branch',{cwd:wt,shell:'/bin/bash'});artifact(main,'T1',{target:'a.js',test_command:'true',changed_lines:[1],worktree:wt});const cli=resolve(import.meta.dir,'../x-build/lib/x-build-cli.mjs'),result=spawnSync('bun',[cli,'mutate','--project','p','--task','T1','--max-mutants','1','--json'],{cwd:main,encoding:'utf8'});expect(result.status).toBe(0);expect(JSON.parse(result.stdout)).toMatchObject({project:'p',counts:{survived:1}});expect(readFileSync(join(main,'a.js'),'utf8')).toBe('const main = true;');expect(readFileSync(join(wt,'a.js'),'utf8')).toBe('const branch = false;');expect(existsSync(join(main,'.xm/review/mutate/p/T1.json'))).toBe(true);expect(existsSync(join(wt,'.xm'))).toBe(false);});

test('small budgets rotate across mutation classes',()=>{const rows=simpleMutations('true === false; 3 < 4 && 5 > 2',{changedLines:[1],maxMutants:5});expect(rows.map(row=>row.operator)).toEqual(['boolean','comparison','relational','logical','numeric']);});

test('build mutation surface has no stale probe command or module references',()=>{const repo=resolve(import.meta.dir,'..');for(const file of ['x-build/lib/x-build-cli.mjs','x-build/lib/x-build/mutate.mjs','x-build/skills/build/references/commands.md','xm/lib/x-build-cli.mjs','xm/lib/x-build/mutate.mjs','xm/skills/build/references/commands.md']){const source=readFileSync(resolve(repo,file),'utf8');expect(source).not.toMatch(/xm build probe|cmdProbe|runTaskProbe|x-build\/probe\.mjs|source:\s*['"]probe/);}});

test('candidate listing includes friendly task metadata and runnable reasons without mutation',()=>{const root=makeRoot();commit(root,'a.js','const value = true;');tasks(root,'app',[{id:'T1',name:'Validate checkout',status:'ready',expected_files:['a.js']},{id:'T2',name:'Docs only',status:'pending',expected_files:['README.md']}]);artifact(root,'T1',{target:'a.js',test_command:'true',changed_lines:[1]},'app');const before=readFileSync(join(root,'a.js'),'utf8'),rows=listMutationTasks(root,root);expect(rows[0]).toMatchObject({project:'app',id:'T1',name:'Validate checkout',status:'ready',files:['a.js'],runnable:true,reason:null});expect(rows.find(row=>row.id==='T2')).toMatchObject({runnable:false,reason:'missing worktree artifact'});expect(readFileSync(join(root,'a.js'),'utf8')).toBe(before);expect(existsSync(join(root,'.xm/review'))).toBe(false);});

test('no-argument CLI prints candidates and list JSON is machine-readable',()=>{const root=makeRoot();commit(root,'a.js','const value = true;');tasks(root,'app',[{id:'T1',name:'Validate checkout',status:'ready',expected_files:['a.js']}]);artifact(root,'T1',{target:'a.js',test_command:'true',changed_lines:[1]},'app');const cli=resolve(import.meta.dir,'../x-build/lib/x-build-cli.mjs'),human=spawnSync('bun',[cli,'mutate'],{cwd:root,encoding:'utf8'}),json=spawnSync('bun',[cli,'mutate','--list','--json'],{cwd:root,encoding:'utf8'});expect(human.status).toBe(0);expect(human.stdout).toContain('app/T1 — Validate checkout');expect(JSON.parse(json.stdout)).toMatchObject({runnable_count:1,tasks:[{project:'app',id:'T1',name:'Validate checkout',runnable:true}]});expect(existsSync(join(root,'.xm/review'))).toBe(false);});

test('no runnable tasks produce a short reason summary instead of history spam',()=>{const root=makeRoot();commit(root,'a.js','const value = true;');tasks(root,'old',[{id:'T1',name:'Old task',status:'completed',expected_files:['a.js']},{id:'T2',name:'Another old task',status:'completed',expected_files:['a.js']}]);const cli=resolve(import.meta.dir,'../x-build/lib/x-build-cli.mjs'),result=spawnSync('bun',[cli,'mutate'],{cwd:root,encoding:'utf8'}),lines=result.stdout.trim().split('\n');expect(result.status).toBe(0);expect(lines.length).toBeLessThanOrEqual(5);expect(result.stdout).toContain('No tasks are ready for mutation testing.');expect(result.stdout).toContain('2 missing worktree artifact');expect(result.stdout).not.toContain('old/T1');});

test('duplicate task ids require project disambiguation',async()=>{const root=makeRoot();commit(root,'a.js','const value = true;');for(const project of ['alpha','beta']){tasks(root,project,[{id:'T1',name:project,status:'ready',expected_files:['a.js']}]);artifact(root,'T1',{target:'a.js',test_command:'true',changed_lines:[1]},project);}await expect(runTaskMutate(root,'T1',{maxMutants:1})).rejects.toThrow(/ambiguous/);expect((await runTaskMutate(root,'T1',{project:'alpha',maxMutants:1})).counts.survived).toBe(1);});
test('project and task traversal are rejected at the engine boundary',async()=>{const root=makeRoot();await expect(runTaskMutate(root,'../task')).rejects.toThrow(/must not contain/);await expect(runTaskMutate(root,'T1',{project:'../project'})).rejects.toThrow(/must not contain/);});
test('missing, primary, or foreign task worktrees fail closed',async()=>{const root=makeRoot(),foreign=makeRoot('mutate-foreign-'),dir=join(root,'.xm/build/projects/p/worktrees/T1');commit(root,'a.js','const value = true;');commit(foreign,'a.js','const foreign = true;');mkdirSync(dir,{recursive:true});writeFileSync(join(dir,'run.json'),JSON.stringify({task_id:'T1',branch:'missing',worktree:'',target:'a.js',test_command:'true',changed_lines:[1]}));await expect(runTaskMutate(root,'T1')).rejects.toThrow(/missing its worktree/);writeFileSync(join(dir,'run.json'),JSON.stringify({task_id:'T1',branch:'master',worktree:root,target:'a.js',test_command:'true',changed_lines:[1]}));await expect(runTaskMutate(root,'T1')).rejects.toThrow(/primary checkout/);writeFileSync(join(dir,'run.json'),JSON.stringify({task_id:'T1',branch:'master',worktree:foreign,target:'a.js',test_command:'true',changed_lines:[1]}));await expect(runTaskMutate(root,'T1')).rejects.toThrow(/different repository/);});
test('project and task path segments cannot collide',async()=>{const root=makeRoot();commit(root,'a.js','const value = true;');for(const [project,task] of [['a-b','c'],['a','b-c']]){tasks(root,project,[{id:task,name:project,status:'ready',expected_files:['a.js']}]);artifact(root,task,{target:'a.js',test_command:'true',changed_lines:[1]},project);await runTaskMutate(root,task,{project,maxMutants:1});}expect(existsSync(join(root,'.xm/review/mutate/a-b/c.json'))).toBe(true);expect(existsSync(join(root,'.xm/review/mutate/a/b-c.json'))).toBe(true);});
test('pre-created predictable temp symlink is never followed',async()=>{const root=makeRoot(),outside=join(root,'outside.txt');commit(root,'a.js','const value = true;');writeFileSync(outside,'sentinel');artifact(root,'T1',{target:'a.js',test_command:'false',changed_lines:[1]});const dir=join(root,'.xm/review/mutate/p');mkdirSync(dir,{recursive:true});const legacy=join(dir,'T1.json.tmp-'+process.pid);symlinkSync(outside,legacy);await expect(runTaskMutate(root,'T1')).rejects.toThrow(/baseline is not green/);expect(readFileSync(outside,'utf8')).toBe('sentinel');expect(lstatSync(legacy).isSymbolicLink()).toBe(true);expect(JSON.parse(readFileSync(join(dir,'T1.json'),'utf8'))).toMatchObject({project:'p',task_id:'T1'});});
test('report publication rejects a group-writable project directory',async()=>{if(process.platform==='win32')return;const root=makeRoot('mutate-report-mode-');commit(root,'a.js','const value = true;');artifact(root,'T1',{target:'a.js',test_command:'false',changed_lines:[1]},'p');const dir=join(root,'.xm/review/mutate/p');mkdirSync(dir,{recursive:true});execSync(`chmod 0777 ${JSON.stringify(dir)}`);await expect(runTaskMutate(root,'T1',{project:'p'})).rejects.toThrow(/report directory is unsafe/);expect(existsSync(join(dir,'T1.json'))).toBe(false);});
test('a concurrent mutation run is rejected while the holder owns the task lock',async()=>{const root=makeRoot('mutate-lock-');commit(root,'a.js','const value = true;');const marker=join(root,'holder-ready'),release=join(root,'release-holder');artifact(root,'T1',{target:'a.js',test_command:`touch ${JSON.stringify(marker)}; while [ ! -e ${JSON.stringify(release)} ]; do sleep 0.02; done`,changed_lines:[1]});const cli=resolve(import.meta.dir,'../x-build/lib/x-build-cli.mjs'),holder=spawn('bun',[cli,'mutate','--project','p','--task','T1','--max-mutants','1','--json'],{cwd:root,stdio:['ignore','pipe','pipe']});let holderOut='',holderErr='';holder.stdout.setEncoding('utf8').on('data',chunk=>{holderOut+=chunk;});holder.stderr.setEncoding('utf8').on('data',chunk=>{holderErr+=chunk;});for(let attempt=0;attempt<100&&!existsSync(marker);attempt+=1)await new Promise(done=>setTimeout(done,20));expect(existsSync(marker)).toBe(true);const contender=spawnSync('bun',[cli,'mutate','--project','p','--task','T1','--max-mutants','1','--json'],{cwd:root,encoding:'utf8'});expect(contender.status).toBe(2);expect(contender.stderr).toContain('mutation already running');writeFileSync(release,'go');const holderExit=await new Promise(resolveExit=>holder.once('close',resolveExit));expect(holderExit).toBe(0);expect(holderErr).toBe('');expect(JSON.parse(holderOut)).toMatchObject({project:'p',task_id:'T1'});const third=spawnSync('bun',[cli,'mutate','--project','p','--task','T1','--max-mutants','1','--json'],{cwd:root,encoding:'utf8'});expect(third.status).toBe(0);});
test('task-level target swap restores the bound inode without following the replacement symlink',async()=>{const root=makeRoot('mutate-swap-'),outside=join(root,'outside.txt'),displacedName='displaced.js';commit(root,'a.js','const value = true;');writeFileSync(outside,'sentinel');const wt=artifact(root,'T1',{target:'a.js',test_command:`if grep -q false a.js; then mv a.js ${displacedName}; ln -s ${JSON.stringify(outside)} a.js; fi`,changed_lines:[1]});await expect(runTaskMutate(root,'T1',{project:'p',maxMutants:1})).rejects.toThrow(/pathname changed/);expect(readFileSync(outside,'utf8')).toBe('sentinel');expect(readFileSync(join(wt,displacedName),'utf8')).toBe('const value = true;');expect(lstatSync(join(wt,'a.js')).isSymbolicLink()).toBe(true);});
test('one linked worktree cannot be claimed by two task artifacts',async()=>{const root=makeRoot('mutate-claim-');commit(root,'a.js','const value = true;');const wt=artifact(root,'T2',{target:'a.js',test_command:'true',changed_lines:[1]},'p');const branch=execSync('git branch --show-current',{cwd:wt,encoding:'utf8'}).trim(),dir=join(root,'.xm/build/projects/p/worktrees/T1');mkdirSync(dir,{recursive:true});writeFileSync(join(dir,'run.json'),JSON.stringify({task_id:'T1',branch,worktree:wt,target:'a.js',test_command:'true',changed_lines:[1]}));await expect(runTaskMutate(root,'T1',{project:'p'})).rejects.toThrow(/claimed by another task/);});
test('recorded branch must match the registered linked worktree',async()=>{const root=makeRoot('mutate-branch-');commit(root,'a.js','const value = true;');const wt=artifact(root,'T1',{target:'a.js',test_command:'true',changed_lines:[1]},'p'),run=join(root,'.xm/build/projects/p/worktrees/T1/run.json'),data=JSON.parse(readFileSync(run,'utf8'));writeFileSync(run,JSON.stringify({...data,branch:'wrong-branch'}));await expect(runTaskMutate(root,'T1',{project:'p'})).rejects.toThrow(/recorded branch/);expect(readFileSync(join(wt,'a.js'),'utf8')).toBe('const value = true;');});
test('cmdMutate accepts project without dispatcher preprocessing',()=>{const root=makeRoot('mutate-direct-cli-');commit(root,'a.js','const value = true;');artifact(root,'T1',{target:'a.js',test_command:'true',changed_lines:[1]},'p');const runner=join(root,'direct.mjs'),moduleUrl=new URL('../x-build/lib/x-build/mutate.mjs',import.meta.url).href;writeFileSync(runner,`import { cmdMutate } from ${JSON.stringify(moduleUrl)}; await cmdMutate(['--project','p','--task','T1','--max-mutants','1','--json']);`);const result=spawnSync('bun',[runner],{cwd:root,encoding:'utf8'});expect(result.status).toBe(0);expect(JSON.parse(result.stdout)).toMatchObject({project:'p',task_id:'T1'});});
test('baseline interruption exits 130',async()=>{const root=makeRoot('mutate-interrupt-');commit(root,'a.js','const value = true;');const marker=join(root,'baseline-ready');artifact(root,'T1',{target:'a.js',test_command:`touch ${JSON.stringify(marker)}; sleep 30`,changed_lines:[1]},'p');const cli=resolve(import.meta.dir,'../x-build/lib/x-build-cli.mjs'),child=spawn('bun',[cli,'mutate','--project','p','--task','T1','--max-mutants','1','--json'],{cwd:root,stdio:['ignore','pipe','pipe']});let stdout='',stderr='';child.stdout.setEncoding('utf8').on('data',chunk=>{stdout+=chunk;});child.stderr.setEncoding('utf8').on('data',chunk=>{stderr+=chunk;});for(let attempt=0;attempt<100&&!existsSync(marker);attempt+=1)await new Promise(done=>setTimeout(done,20));expect(existsSync(marker)).toBe(true);child.kill('SIGINT');const code=await new Promise(resolveCode=>child.once('close',resolveCode));expect(code).toBe(130);expect(stderr).toBe('');expect(JSON.parse(stdout)).toMatchObject({baseline_outcome:'skipped'});});
test('contextual multi-file artifact diff mutates only added lines for its target',async()=>{const root=makeRoot('mutate-diff-');commit(root,'a.js','const untouched = true;\nconst changed = false;');const diff=['diff --git a/other.js b/other.js','--- a/other.js','+++ b/other.js','@@ -1 +1 @@','-const other = false;','+const other = true;','diff --git a/a.js b/a.js','--- a/a.js','+++ b/a.js','@@ -1,2 +1,2 @@',' const untouched = true;','-const changed = true;','+const changed = false;'].join('\n');artifact(root,'T1',{target:'a.js',test_command:'true',diff},'p');const report=await runTaskMutate(root,'T1',{project:'p'});expect(report.mutants.length).toBeGreaterThan(0);expect(report.mutants.every(row=>row.line===2)).toBe(true);});
test('discovery rejects tasks with no mutation candidate',()=>{const root=makeRoot('mutate-no-candidate-');commit(root,'a.js','const value = true;');tasks(root,'p',[{id:'T1',name:'No changed operator',status:'ready',expected_files:['a.js']}]);artifact(root,'T1',{target:'a.js',test_command:'true',changed_lines:[99]},'p');expect(listMutationTasks(root,root)[0]).toMatchObject({runnable:false,reason:'no supported mutation on changed lines'});});
test('task metadata changed during baseline is revalidated before mutation',async()=>{const root=makeRoot('mutate-refresh-');commit(root,'a.js','const value = true;');const wt=artifact(root,'T1',{target:'a.js',test_command:'true',changed_lines:[1]},'p'),run=join(root,'.xm/build/projects/p/worktrees/T1/run.json'),data=JSON.parse(readFileSync(run,'utf8')),script=join(root,'change-run.cjs');writeFileSync(script,`const fs=require('fs');const p=${JSON.stringify(run)};const d=JSON.parse(fs.readFileSync(p));d.branch='changed-during-baseline';fs.writeFileSync(p,JSON.stringify(d));`);writeFileSync(run,JSON.stringify({...data,test_command:`node ${JSON.stringify(script)}`}));await expect(runTaskMutate(root,'T1',{project:'p',maxMutants:1})).rejects.toThrow(/recorded branch/);expect(readFileSync(join(wt,'a.js'),'utf8')).toBe('const value = true;');});
test('every target is protected and same-inode conflicts are preserved',async()=>{const root=makeRoot('mutate-multi-protect-');commit(root,'a.js','const a = true;');writeFileSync(join(root,'b.js'),'const b = true;');execSync('git add b.js && git commit -qm second',{cwd:root,shell:'/bin/bash'});const wt=artifact(root,'T1',{test_command:`if grep -q false a.js; then printf 'const b = false;' > b.js; fi`,changed_lines:[1]},'p');tasks(root,'p',[{id:'T1',name:'Protect all targets',status:'ready',expected_files:['a.js','b.js']}]);const run=join(root,'.xm/build/projects/p/worktrees/T1/run.json'),data=JSON.parse(readFileSync(run,'utf8'));writeFileSync(run,JSON.stringify({...data,task:{expected_files:['a.js','b.js']}}));await expect(runTaskMutate(root,'T1',{project:'p',maxMutants:1})).rejects.toThrow(/changed concurrently/);expect(readFileSync(join(wt,'a.js'),'utf8')).toBe('const a = true;');expect(readFileSync(join(wt,'b.js'),'utf8')).toBe('const b = false;');});
