import { test, expect } from 'bun:test'; import { execSync } from 'node:child_process'; import { mkdtempSync, writeFileSync, readFileSync, mkdirSync, existsSync, lstatSync } from 'node:fs'; import { tmpdir } from 'node:os'; import { join } from 'node:path'; import { runMutate, runTaskMutate, simpleMutations } from '../x-build/lib/x-build/mutate.mjs';
function taskFixture(prefix,source){const root=mkdtempSync(join(tmpdir(),prefix));execSync('git init -q && git config user.email test@example.com && git config user.name Test',{cwd:root,shell:'/bin/bash'});writeFileSync(join(root,'a.js'),source);execSync('git add a.js && git commit -qm base',{cwd:root,shell:'/bin/bash'});const wt=root+'-wt',branch='mutate-'+Date.now()+'-'+Math.random().toString(16).slice(2);execSync(`git worktree add -qb ${JSON.stringify(branch)} ${JSON.stringify(wt)}`,{cwd:root,shell:'/bin/bash'});const d=join(root,'.xm/build/projects/p/worktrees/T1');mkdirSync(d,{recursive:true});return {root,wt,branch,d};}
test('a passing test means the mutant survived and source bytes restore',async()=>{const root=mkdtempSync(join(tmpdir(),'mutate-')),p=join(root,'a.js');writeFileSync(p,'original');const result=await runMutate({target:p,command:'true',cwd:root});expect(result.outcome).toBe('survived');expect(readFileSync(p,'utf8')).toBe('original');});
test('a failing test means the mutant was killed',async()=>{const root=mkdtempSync(join(tmpdir(),'mutate-')),p=join(root,'a.js');writeFileSync(p,'original');const result=await runMutate({target:p,command:'false',cwd:root});expect(result.outcome).toBe('killed');});
test('direct runner restores the bound inode without following a replacement symlink',async()=>{const root=mkdtempSync(join(tmpdir(),'mutate-swap-')),p=join(root,'a.js'),moved=join(root,'moved.js'),outside=join(root,'outside.txt');writeFileSync(p,'original');writeFileSync(outside,'sentinel');await expect(runMutate({target:p,command:`mv a.js moved.js; ln -s ${JSON.stringify(outside)} a.js`,cwd:root})).rejects.toThrow(/pathname changed/);expect(readFileSync(outside,'utf8')).toBe('sentinel');expect(readFileSync(moved,'utf8')).toBe('original');expect(lstatSync(p).isSymbolicLink()).toBe(true);});
test('task mutate mutates only declared changed lines and writes a report',async()=>{const {root,wt,branch,d}=taskFixture('mutate-task-','const untouched = true;\nconst changed = false === true; return 3;');writeFileSync(join(d,'run.json'),JSON.stringify({task_id:'T1',branch,target:'a.js',test_command:'true',changed_lines:[2],worktree:wt}));const report=await runTaskMutate(root,'T1');expect(report).toMatchObject({project:'p',task_id:'T1'});expect(report.mutants.length).toBeGreaterThan(1);expect(report.mutants.every(row=>row.line===2)).toBe(true);expect(report.counts.survived).toBe(report.mutants.length);expect(existsSync(join(root,'.xm/review/mutate/p/T1.json'))).toBe(true);expect(readFileSync(join(wt,'a.js'),'utf8')).toBe('const untouched = true;\nconst changed = false === true; return 3;');});
test('wall budget marks remaining mutants skipped',async()=>{const {root,wt,branch,d}=taskFixture('mutate-budget-','true === false; 3;');writeFileSync(join(d,'run.json'),JSON.stringify({task_id:'T1',branch,target:'a.js',test_command:'true',changed_lines:[1],worktree:wt}));const report=await runTaskMutate(root,'T1',{maxDurationMs:0});expect(report.mutants.every(row=>row.outcome==='skipped')).toBe(true);});
test('simple mutations span supported classes',()=>{const kinds=new Set(simpleMutations('true === false; 3').map(row=>row.operator));expect(kinds).toContain('boolean');expect(kinds).toContain('comparison');expect(kinds).toContain('numeric');});
test('simple mutations honor changed lines and max count',()=>{const rows=simpleMutations('true;\nfalse === true; 3',{changedLines:[2],maxMutants:2});expect(rows).toHaveLength(2);expect(rows.every(row=>row.line===2)).toBe(true);});
test('abort kills the test group and restores exact bytes',async()=>{const root=mkdtempSync(join(tmpdir(),'mutate-abort-')),p=join(root,'a.js');writeFileSync(p,'original');const controller=new AbortController();setTimeout(()=>controller.abort(),25);const result=await runMutate({target:p,command:`echo changed > ${p}; sleep 5`,cwd:root,timeoutMs:5000,signal:controller.signal});expect(result.outcome).toBe('skipped');expect(readFileSync(p,'utf8')).toBe('original');});
