import { afterEach, expect, test } from 'bun:test';
import { execSync, spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { listMutationTasks, runTaskMutate, simpleMutations } from '../x-build/lib/x-build/mutate.mjs';

const roots=[];
const makeRoot=(prefix='mutate-audit-')=>{const root=mkdtempSync(join(tmpdir(),prefix));roots.push(root);execSync('git init -q && git config user.email test@example.com && git config user.name Test',{cwd:root,shell:'/bin/bash'});return root;};
const commit=(root,file,content)=>{writeFileSync(join(root,file),content);execSync(`git add ${JSON.stringify(file)} && git commit -qm fixture`,{cwd:root,shell:'/bin/bash'});};
const artifact=(state,task,data,project='p')=>{const dir=join(state,'.xm/build/projects',project,'worktrees',task);mkdirSync(dir,{recursive:true});writeFileSync(join(dir,'run.json'),JSON.stringify(data));};
const tasks=(state,project,rows)=>{const dir=join(state,'.xm/build/projects',project,'phases/02-plan');mkdirSync(dir,{recursive:true});writeFileSync(join(dir,'tasks.json'),JSON.stringify({tasks:rows}));};
afterEach(()=>{for(const root of roots.splice(0))try{rmSync(root,{recursive:true,force:true});}catch{}});

test('non-green baseline exits 2 before mutants or ledger rows',async()=>{const root=makeRoot();commit(root,'a.js','const value = true;');artifact(root,'T1',{target:'a.js',test_command:'false',changed_lines:[1]});let error;try{await runTaskMutate(root,'T1');}catch(caught){error=caught;}expect(error?.exitCode).toBe(2);expect(error?.report).toMatchObject({baseline_exit_code:1,mutants:[]});expect(existsSync(join(root,'.xm/review/escape-ledger.jsonl'))).toBe(false);expect(JSON.parse(readFileSync(join(root,'.xm/review/mutate-T1.json'),'utf8')).mutants).toEqual([]);});

test('detected package script runs through bun run test',async()=>{const root=makeRoot();commit(root,'a.js','const value = true;');writeFileSync(join(root,'package.json'),JSON.stringify({scripts:{test:'touch script-ran'}}));writeFileSync(join(root,'bun.lock'),'');artifact(root,'T1',{target:'a.js',changed_lines:[1]});const report=await runTaskMutate(root,'T1',{maxMutants:1});expect(report).toMatchObject({baseline_exit_code:0,test_command:'bun run test',test_command_source:'package:bun'});expect(existsSync(join(root,'script-ran'))).toBe(true);});

test('symlink target is rejected before external bytes change',async()=>{const root=makeRoot(),outside=join(tmpdir(),`mutate-outside-${process.pid}-${Date.now()}.js`);writeFileSync(outside,'const external = true;');symlinkSync(outside,join(root,'a.js'));execSync('git add a.js && git commit -qm symlink',{cwd:root,shell:'/bin/bash'});artifact(root,'T1',{target:'a.js',test_command:'true',changed_lines:[1]});try{await expect(runTaskMutate(root,'T1')).rejects.toThrow(/non-symlink/);expect(readFileSync(outside,'utf8')).toBe('const external = true;');}finally{rmSync(outside,{force:true});}});

test('linked worktree mutates branch bytes but stores report in main state root',async()=>{const main=makeRoot('mutate-main-');commit(main,'a.js','const main = true;');const wt=main+'-wt';roots.push(wt);execSync(`git worktree add -qb feature ${JSON.stringify(wt)}`,{cwd:main,shell:'/bin/bash'});writeFileSync(join(wt,'a.js'),'const branch = false;');execSync('git add a.js && git commit -qm branch',{cwd:wt,shell:'/bin/bash'});artifact(main,'T1',{target:'a.js',test_command:'true',changed_lines:[1]});const report=await runTaskMutate(main,'T1',{workspaceRoot:wt,stateRoot:main,maxMutants:1});expect(report.counts.survived).toBe(1);expect(readFileSync(join(main,'a.js'),'utf8')).toBe('const main = true;');expect(readFileSync(join(wt,'a.js'),'utf8')).toBe('const branch = false;');expect(existsSync(join(main,'.xm/review/mutate-T1.json'))).toBe(true);expect(existsSync(join(wt,'.xm/review/mutate-T1.json'))).toBe(false);});

test('linked-worktree mutate CLI resolves main state and current source',()=>{const main=makeRoot('mutate-cli-main-');commit(main,'a.js','const main = true;');const wt=main+'-wt';roots.push(wt);execSync(`git worktree add -qb cli-feature ${JSON.stringify(wt)}`,{cwd:main,shell:'/bin/bash'});writeFileSync(join(wt,'a.js'),'const branch = false;');execSync('git add a.js && git commit -qm branch',{cwd:wt,shell:'/bin/bash'});artifact(main,'T1',{target:'a.js',test_command:'true',changed_lines:[1]});const cli=resolve(import.meta.dir,'../x-build/lib/x-build-cli.mjs'),result=spawnSync('bun',[cli,'mutate','--task','T1','--max-mutants','1','--json'],{cwd:wt,encoding:'utf8'});expect(result.status).toBe(0);expect(JSON.parse(result.stdout).counts.survived).toBe(1);expect(readFileSync(join(main,'a.js'),'utf8')).toBe('const main = true;');expect(readFileSync(join(wt,'a.js'),'utf8')).toBe('const branch = false;');expect(existsSync(join(main,'.xm/review/mutate-T1.json'))).toBe(true);expect(existsSync(join(wt,'.xm'))).toBe(false);});

test('small budgets rotate across mutation classes',()=>{const rows=simpleMutations('true === false; 3 < 4 && 5 > 2',{changedLines:[1],maxMutants:5});expect(rows.map(row=>row.operator)).toEqual(['boolean','comparison','relational','logical','numeric']);});

test('build mutation surface has no stale probe command or module references',()=>{const repo=resolve(import.meta.dir,'..');for(const file of ['x-build/lib/x-build-cli.mjs','x-build/lib/x-build/mutate.mjs','x-build/skills/build/references/commands.md','xm/lib/x-build-cli.mjs','xm/lib/x-build/mutate.mjs','xm/skills/build/references/commands.md']){const source=readFileSync(resolve(repo,file),'utf8');expect(source).not.toMatch(/xm build probe|cmdProbe|runTaskProbe|x-build\/probe\.mjs|source:\s*['"]probe/);}});

test('candidate listing includes friendly task metadata and runnable reasons without mutation',()=>{const root=makeRoot();commit(root,'a.js','const value = true;');tasks(root,'app',[{id:'T1',name:'Validate checkout',status:'ready',expected_files:['a.js']},{id:'T2',name:'Docs only',status:'pending',expected_files:['README.md']}]);artifact(root,'T1',{target:'a.js',test_command:'true',changed_lines:[1]},'app');const before=readFileSync(join(root,'a.js'),'utf8'),rows=listMutationTasks(root,root);expect(rows[0]).toMatchObject({project:'app',id:'T1',name:'Validate checkout',status:'ready',files:['a.js'],runnable:true,reason:null});expect(rows.find(row=>row.id==='T2')).toMatchObject({runnable:false,reason:'missing worktree artifact'});expect(readFileSync(join(root,'a.js'),'utf8')).toBe(before);expect(existsSync(join(root,'.xm/review'))).toBe(false);});

test('no-argument CLI prints candidates and list JSON is machine-readable',()=>{const root=makeRoot();commit(root,'a.js','const value = true;');tasks(root,'app',[{id:'T1',name:'Validate checkout',status:'ready',expected_files:['a.js']}]);artifact(root,'T1',{target:'a.js',test_command:'true',changed_lines:[1]},'app');const cli=resolve(import.meta.dir,'../x-build/lib/x-build-cli.mjs'),human=spawnSync('bun',[cli,'mutate'],{cwd:root,encoding:'utf8'}),json=spawnSync('bun',[cli,'mutate','--list','--json'],{cwd:root,encoding:'utf8'});expect(human.status).toBe(0);expect(human.stdout).toContain('app/T1 — Validate checkout');expect(JSON.parse(json.stdout)).toMatchObject({runnable_count:1,tasks:[{project:'app',id:'T1',name:'Validate checkout',runnable:true}]});expect(existsSync(join(root,'.xm/review'))).toBe(false);});

test('no runnable tasks produce a short reason summary instead of history spam',()=>{const root=makeRoot();commit(root,'a.js','const value = true;');tasks(root,'old',[{id:'T1',name:'Old task',status:'completed',expected_files:['a.js']},{id:'T2',name:'Another old task',status:'completed',expected_files:['a.js']}]);const cli=resolve(import.meta.dir,'../x-build/lib/x-build-cli.mjs'),result=spawnSync('bun',[cli,'mutate'],{cwd:root,encoding:'utf8'}),lines=result.stdout.trim().split('\n');expect(result.status).toBe(0);expect(lines.length).toBeLessThanOrEqual(5);expect(result.stdout).toContain('No tasks are ready for mutation testing.');expect(result.stdout).toContain('2 missing worktree artifact');expect(result.stdout).not.toContain('old/T1');});

test('duplicate task ids require project disambiguation',async()=>{const root=makeRoot();commit(root,'a.js','const value = true;');for(const project of ['alpha','beta']){tasks(root,project,[{id:'T1',name:project,status:'ready',expected_files:['a.js']}]);artifact(root,'T1',{target:'a.js',test_command:'true',changed_lines:[1]},project);}await expect(runTaskMutate(root,'T1',{maxMutants:1})).rejects.toThrow(/ambiguous/);expect((await runTaskMutate(root,'T1',{project:'alpha',maxMutants:1})).counts.survived).toBe(1);});
